# cloudbuild.yaml
steps:
  - name: python
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']

  - name: python
    entrypoint: uvicorn
    args: ['main:app', '--host=0.0.0.0', '--port=8080']

timeout: "900s"
