name: Deploy to Cloud Run (No Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy FastAPI (Cloud Build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cvoapi
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Write GCP Credentials to key.json
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > key.json

      - name: Authenticate with Service Account
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project cvoapi

      - name: Submit Cloud Build using cloudbuild.yaml
        run: gcloud builds submit --config cloudbuild.yaml

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service \
            --image gcr.io/cvoapi/fastapi-app \
            --region us-central1 \
            --platform managed \
            --quiet

      - name: Set IAM Policy to allow access
        run: |
          gcloud run services add-iam-policy-binding fastapi-service \
            --region=us-central1 \
            --member="allAuthenticatedUsers" \
            --role="roles/run.invoker"
