name: Deploy to Cloud Run (No Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy FastAPI (Cloud Build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cvoapi
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Submit Cloud Build using cloudbuild.yaml
        run: gcloud builds submit --config cloudbuild.yaml
